server:
  port: 8080
  address: 0.0.0.0
  # address: 127.0.0.1
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xx.xxx.xx.xxx:3306/myself_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: xxxxxx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  data:
    redis:
      host: xx.xxx.xx.xxx
      port: 0000
      database: 0
      password: xxxxxxx
      connect-timeout: 5s
      timeout: 5s
      # Lettuce 客户端的配置
      lettuce:
        # 连接池配置
        pool:
          # 最小空闲连接
          min-idle: 0
          # 最大空闲连接
          max-idle: 8
          # 最大活跃连接
          max-active: 8
          # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
          max-wait: -1ms
  security:
    user:
      name: shusheng007
      password: ss007
logging:
  level:
    org:
      springframework:
        security: DEBUG
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.example.demo.entity

knife4j:
  enable: true
  setting:
    language: zh_cn